version: "3.8"

services:
  postgres:
    image: postgres:18
    container_name: tap-ddd-pg
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tap_ddd
    ports:
      - "5432:5432"
    volumes:
      - tap_pg_data:/var/lib/postgresql

volumes:
  tap_pg_data:
